var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/osce/events/[id]/student-agencies/route.js")
R.c("server/chunks/[root-of-the-server]__51972479._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/[root-of-the-server]__2d48b7f9._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/[root-of-the-server]__d6dcdb21._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/040eb_server_app_api_osce_events_[id]_student-agencies_route_actions_1580eb7d.js")
R.m(789358)
module.exports=R.m(789358).exports
