var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/lab-management/template-reviews/[id]/finalize/route.js")
R.c("server/chunks/[root-of-the-server]__2f101475._.js")
R.c("server/chunks/[root-of-the-server]__5c9d265a._.js")
R.c("server/chunks/e71d5_next_dist_0bb58a65._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__48e44030._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/669f3_app_api_lab-management_template-reviews_[id]_finalize_route_actions_f85f6eef.js")
R.m(244697)
module.exports=R.m(244697).exports
