var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cases/generate/route.js")
R.c("server/chunks/[root-of-the-server]__5c9d265a._.js")
R.c("server/chunks/[root-of-the-server]__c7132cdb._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/e71d5_next_dist_0bb58a65._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__48e44030._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/e71d5_@anthropic-ai_sdk_index_mjs_d99c6343._.js")
R.c("server/chunks/d9de2__next-internal_server_app_api_cases_generate_route_actions_ade8d03f.js")
R.m(81646)
module.exports=R.m(81646).exports
