var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/dashboard-defaults/route.js")
R.c("server/chunks/[root-of-the-server]__513ec9b7._.js")
R.c("server/chunks/[root-of-the-server]__5c9d265a._.js")
R.c("server/chunks/e71d5_next_dist_0bb58a65._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__48e44030._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/d9de2__next-internal_server_app_api_admin_dashboard-defaults_route_actions_4a365b4c.js")
R.m(953350)
module.exports=R.m(953350).exports
