var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/lab-management/students/[id]/clinical-tasks/route.js")
R.c("server/chunks/[root-of-the-server]__2e89d0b2._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/[root-of-the-server]__2d48b7f9._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/[root-of-the-server]__d6dcdb21._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/669f3_app_api_lab-management_students_[id]_clinical-tasks_route_actions_9ceca00d.js")
R.m(127580)
module.exports=R.m(127580).exports
