var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/lab-management/lab-days/[id]/debrief/route.js")
R.c("server/chunks/[root-of-the-server]__bcd180b1._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/[root-of-the-server]__2d48b7f9._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/[root-of-the-server]__d6dcdb21._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/040eb_server_app_api_lab-management_lab-days_[id]_debrief_route_actions_e5448140.js")
R.m(367210)
module.exports=R.m(367210).exports
