var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/data-exports/[id]/download/route.js")
R.c("server/chunks/[root-of-the-server]__a085ce06._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/[root-of-the-server]__2d48b7f9._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/[root-of-the-server]__d6dcdb21._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/040eb_server_app_api_admin_data-exports_[id]_download_route_actions_8e01185a.js")
R.m(56092)
module.exports=R.m(56092).exports
