var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/cron/internship-milestones/route.js")
R.c("server/chunks/e71d5_next_dist_esm_build_templates_app-route_25c25db5.js")
R.c("server/chunks/e71d5_next_dist_0bb58a65._.js")
R.c("server/chunks/[root-of-the-server]__01fb35d2._.js")
R.c("server/chunks/[root-of-the-server]__48e44030._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/d9de2__next-internal_server_app_api_cron_internship-milestones_route_actions_679ab959.js")
R.m(363693)
module.exports=R.m(363693).exports
