var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/osce/admin/students/reorder/route.js")
R.c("server/chunks/[root-of-the-server]__b881c775._.js")
R.c("server/chunks/[root-of-the-server]__5c9d265a._.js")
R.c("server/chunks/e71d5_next_dist_0bb58a65._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/[root-of-the-server]__48e44030._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/043ca_next-internal_server_app_api_osce_admin_students_reorder_route_actions_a88f7ee4.js")
R.m(385863)
module.exports=R.m(385863).exports
