var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/lab-management/skill-drills/[id]/documents/route.js")
R.c("server/chunks/[root-of-the-server]__415ad9c6._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/[root-of-the-server]__2d48b7f9._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/[root-of-the-server]__d6dcdb21._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/669f3_app_api_lab-management_skill-drills_[id]_documents_route_actions_72fc5c2c.js")
R.m(669971)
module.exports=R.m(669971).exports
