var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/compliance/route.js")
R.c("server/chunks/[root-of-the-server]__8fdc7794._.js")
R.c("server/chunks/[root-of-the-server]__d6dcdb21._.js")
R.c("server/chunks/[root-of-the-server]__2d48b7f9._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/2e377_focused-goodall__next-internal_server_app_api_compliance_route_actions_f1035a49.js")
R.m(799993)
module.exports=R.m(799993).exports
