var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/calendar/calendars/route.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_dba90e6a._.js")
R.c("server/chunks/[root-of-the-server]__a5ef78d1._.js")
R.c("server/chunks/e71d5_next_dist_0bb58a65._.js")
R.c("server/chunks/[root-of-the-server]__5c9d265a._.js")
R.c("server/chunks/[root-of-the-server]__6536df96._.js")
R.c("server/chunks/[root-of-the-server]__48e44030._.js")
R.c("server/chunks/e71d5_next_7d129b84._.js")
R.c("server/chunks/_claude_worktrees_focused-goodall_lib_supabase_ts_b99b8956._.js")
R.c("server/chunks/[root-of-the-server]__a801940c._.js")
R.c("server/chunks/d9de2__next-internal_server_app_api_calendar_calendars_route_actions_72a53be1.js")
R.m(553291)
module.exports=R.m(553291).exports
